receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  memory_limiter:
    limit_percentage: 80
    spike_limit_percentage: 25
    check_interval: 15s

exporters:
  otlp:
    endpoint: http://tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    enable_open_metrics: true
  logging:

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [0.5ms, 2ms, 4ms, 8ms, 16ms, 50ms, 100ms, 200ms, 350ms, 500ms, 750ms, 1s, 1.5s, 2s, 5s]
    exemplars:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp, logging, spanmetrics]
    metrics:
      receivers: [spanmetrics]
      processors: [memory_limiter, batch]
      exporters: [prometheus]